### ISSUE TITLE
Not able to handle "~"

### ISSUE THREAD

**Issue by buhtzz** [klieret/RandomFileTree#31]
Using a path with `~` doesn't result in `$HOME` (or `pathlib.Path.home()`) but in a folder named `~`.

E.g. `~/treetest` should be `/home/user/treetest` but results in `./~/treetest`.

Maybe related #27. Here I haven't realized that there was `~` created.

**Comment by klieret** [comment]
Can you show me how you passed in the initial path? Did you pass in `Path("~/a/b/c").expanduser()"?

**Comment by klieret** [comment]
I think this is inline with how the `os` module handles string inputs. For example if you do `os.mkdir("~")`, it will also create a folder with the name `~`

**Comment by buhtzz** [comment]
I simply did 

`randomfiletree.iterative_gaussian_tree('~/basedir')`

and assumed that internally this would be handled correct.
