### ISSUE TITLE
Use github actions instead of travis

### ISSUE THREAD

**Issue by klieret** [klieret/RandomFileTree#6]

**Comment by donheshanthaka** [comment]
Hi, can you assign me this issue, Thank you in advance.

**Comment by klieret** [comment]
Sure. You can probably take [this](https://github.com/klieret/python-cookiecutter/tree/main/%7B%7Bcookiecutter.project_name%7D%7D/.github) as a template. 

(Note that I'm hoping to close this soon though, because testing is crucial for the other issues, so if there is no PR till Saturday I will reassign it to myself, sorry.)
