### ISSUE TITLE
Depth control

### ISSUE THREAD

**Issue by delanym** [klieret/RandomFileTree#69]
With the command
``` shell
randomfiletree croc -f 5 -d 3 --maxdepth 20
```

I get a directory structure 2 levels deep. What if I wanted one with 20 levels?

**Comment by klieret** [comment]
It's probably not possible to easily specify the exact depth. You can get deeper directory structures with the `--repeat` option (take another look at the examples in the readme to see how it works), but the number of created files and directories will scale exponentially (and not just in depth). So I wouldn't run `--repeat 20`. 

So short story, it's currently not reasonably supported with the strategies that are implemented right now.

**Comment by klieret** [comment]
I guess it would be possible to also add a `--maxwidth` argument and then do something like `randomfiletree croc -f 5 -d 3 --maxdepth 20 --maxwidth 2 --repeat 20`, but it's not currently there yet.
